---
# tasks file for bastion

# Use force update get to overcome the apt lock (lock held by another process)

- name: Update machine
  apt:
    update_cache: yes
    force_apt_get: "{{ machine.force }}"

- name: Creates jenkins directory
  file:
    path: /jenkins
    state: directory
    mode: '777'

- name: Install jre
  apt:
    name: "{{ java.package }}"
    force_apt_get: yes

- name: Install ssh
  apt:
    name: "{{ ssh.package }}"
    state: "{{ ssh.state }}"
    force_apt_get: yes
  notify: 
    - start_ssh
