---
# defaults file for bastion



machine:
  version: latest
  force: yes


java:
  state: present
  package: openjdk-11-jre


ssh:
  service_name: sshd
  state: present
  package: openssh-server
  status: started